train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./datasets/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-bicubic
    args:
      inp_size : 32
      gt_size: 64
      augment: true
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: edsr-baseline
  args:
    scale: 2

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 5
epoch_save: 100

mode : 0
is_resume : False
resume: ./save/_train_edsr-baseline-liif/epoch-last.pth