train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-bicubic
    args:
      inp_size : 48
      gt_size: 192
      augment: true
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: edsr-baseline-m
  args:
    scale: 4
    upsample_mode: 'bicubic'

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 5
epoch_save: 100

scale:
  mode: 'multi_arbitrary'
  factor_range: [1, 4]
  

is_resume : True
resume: ./save/train_edsr-baseline-multi/edsr.pth